name       : mininet
version    : 2.3.0.6
release    : 4
source     :
    - https://github.com/mininet/mininet/archive/2.3.0d6.tar.gz : d1cd568bd3e8d951a43a363114499f70b7631883b5144d7d7e1eab1123eadfc3
license    : MIT
summary    : Emulator for rapid prototyping of Software Defined Networks
component  : network.util
description: |
    Emulator for rapid prototyping of Software Defined Networks
builddeps  :
    - pkgconfig(python3)
    - help2man
    - pep8
    - psmisc
    - pyflakes
    - pylint
    - python-pexpect
    - socat
rundeps    :
    - ethtool
    - ifconfig
    - iperf
    - iproute2
    - openssh
    - openvswitch
    - python3
environment: PYTHON=python3 export PYTHON
setup      : |
    %patch -p1 < $pkgfiles/fix-build-dirs.patch
install    : |
    %make_install
